version: '3.7'

services:

#Data Flow
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    ports:
      - '8443:8443'
    volumes:
      - ./volumes/nifi/jdbc:/opt/jdbc
      - ./volumes/nifi/data:/opt/nifi/data
      - ./volumes/nifi/certs/:/opt/certs
      - ./volumes/nifi/logs:/opt/nifi/logs
      - ./volumes/nifi/properties:/opt/nifi/nifi-current/properties  #credentials.properties
      - ./volumes/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./volumes/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./volumes/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./volumes/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
#      SINGLE_USER_CREDENTIALS_USERNAME: admin
#      SINGLE_USER_CREDENTIALS_PASSWORD: 123456789012        # Alterar senha:   ./bin/nifi.sh set-single-user-credentials admin "123456789012"
      AUTH: ldap
      KEYSTORE_PATH: /opt/certs/keystore.jks
      KEYSTORE_TYPE: JKS
      KEYSTORE_PASSWORD: B1GBcMcynhvrQkZ02ZvQdqA/jyqdcZ8EASJesf/KxLM
      TRUSTSTORE_PATH: /opt/certs/truststore.jks
      TRUSTSTORE_PASSWORD: rhdHaoyvhmhISId7Jvees/SYcBtUMVCIW+m/fzTE000
      TRUSTSTORE_TYPE: JKS
      INITIAL_ADMIN_IDENTITY: 'cn=customuser,ou=users,dc=lsc,dc=org'
      LDAP_AUTHENTICATION_STRATEGY: 'SIMPLE'
      LDAP_MANAGER_DN: 'cn=admin,dc=lsc,dc=org'
      LDAP_MANAGER_PASSWORD: 'adminpassword'
      LDAP_USER_SEARCH_BASE: 'dc=lsc,dc=org'
      LDAP_USER_SEARCH_FILTER: 'cn={0}'
      LDAP_IDENTITY_STRATEGY: 'USE_DN'
      LDAP_URL: 'ldap://openldap:1389'
    networks:
      - nifi_network
    depends_on:
      - openldap
#Gerar certificados:
# docker exec -u 0 -it nifi sh -c "/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh standalone -n 'admin.com.org' && mv /opt/nifi/nifi-current/admin.com.org/* /opt/certs/ && mv /opt/nifi/nifi-current/nifi-* /opt/certs/"


#controle de vers찾o para o Nifi
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - '18080:18080'
    volumes:
     - ./volumes/nifi-registry/data:/data
     - ./volumes/nifi-registry/database:/opt/nifi-registry/nifi-registry-current/database
     - ./volumes/nifi-registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
#     - ./volumes/nifi-registry/nifi-registry:/opt/nifi-registry/nifi-registry-current/nifi-registry
#     - ./volumes/nifi-registry/certs:/opt/certs
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: 18080
#      NIFI_REGISTRY_FLOW_PROVIDER: oid
#      NIFI_REGISTRY_GIT_REMOTE_URL: https://github.com/leonardocosouza/nifi.git
#      NIFI_REGISTRY_GIT_USER: 23eecf76865b27304365
#      NIFI_REGISTRY_GIT_PASSWORD: f51428204750142da612fe289d5a1f813768a01c
#      NIFI_REGISTRY_GIT_REPO: /opt/nifi-registry/nifi-registry-current/nifi-registry/nifi
    networks:
      - nifi_network


# Reposit처rio de Dados N찾o Estruturados - Suporte S3
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_STORAGE_USE_HTTPS: False
    networks:
      - nifi_network
    command: server /nifi.properties --console-address ":9001"


# Reposit처rio de Dados Estruturados
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres/data:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    networks:
      - nifi_network


#docker pull bitnami/openldap
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    hostname: openldap
    environment:
      LDAP_ORGANISATION: lsc
      LDAP_DOMAIN: lsc.org
      LDAP_ADMIN_USERNAME: 'admin'
      LDAP_ADMIN_PASSWORD: 'adminpassword'
      LDAP_USERS: 'customuser'
      LDAP_PASSWORDS: 'custompassword'
      LDAP_ROOT: 'dc=lsc,dc=org'
      LDAP_ADMIN_DN: 'cn=admin,dc=lsc,dc=org'
   # volumes:
    #  - ./volumes/openldap:/bitnami/openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    networks:
      - nifi_network
networks:
  nifi_network:
    driver: bridge



#docker exec -it openldap ldapsearch -x -H ldap://openldap:1389 -b "dc=lsc,dc=org" -D "cn=admin,dc=lsc,dc=org" -w adminpassword
